Compliance APIs default to 24h without end_time
Signed-off-by: Alex Pop <apop@chef.io>

diff --git a/components/compliance-service/Makefile b/components/compliance-service/Makefile
--- a/components/compliance-service/Makefile
+++ b/components/compliance-service/Makefile
@@ -123,7 +123,7 @@ gateway-proto:
 wait-for-compliance-service:
 	@printf "\n===> ${blue}Waiting for the compliance service to be ready...${reset}\n"; \
 	i=1; \
-	max_loops=30; \
+	max_loops=50; \
 	printf "\n===> ${blue}Checking Compliance Service version to ensure it's ready to receive connections...${reset}\n"; \
 	$(RUN_GRPCURL_COMPLIANCE_VERSION); \
 	while [ $$? -ne 0 -a $$i -lt $$max_loops ]; do \
@@ -344,7 +344,7 @@ wait-for-ingestion:
 	i=1; \
 	curl_output="-=init=-"; \
 	max_loops=50; \
-	es_docs=35; \
+	es_docs=45; \
 	healthy_match="\"total\":$$es_docs,\"successful\":$$es_docs"; \
 	printf "\n===> ${blue}Checking ElasticSearch to ensure it has ingested our reports${reset}\n"; \
 	curl -s -X GET "$(ELASTICSEARCH_URL)/comp-*-r-20*/_doc/_count" | grep $$healthy_match > /dev/null; \
@@ -415,17 +415,19 @@ test-integration-scanner: start-es start-pg start-ssh-node download-sample-marke
 	fi;
 
 test-automate-upgrade: clean-all
-	printf "\n===> Running Automate upgrade integration tests with TEST=$(TEST)\n"
+	printf "\n===> Running Automate upgrade integration tests\n"
 	@if [ "$(A1_DATA)" != "true" ] && [ "$(A2V1_DATA)" != "true" ] && [ "$(A2V2_DATA)" != "true" ] && [ "$(A2V3_DATA)" != "true" ] && [ "$(A2V4_DATA)" != "true" ] && [ "$(A2V5_DATA)" != "true" ] && [ "$(A2V6_DATA)" != "true" ]; then \
 	  printf "===> ${red}Aborting test-automate-upgrade as one of these ENV variables is not true: A1_DATA, A2V1_DATA, A2V2_DATA, A2V3_DATA, A2V4_DATA, A2V5_DATA, A2V6_DATA${reset}\n"; \
 	  exit 2; \
 	fi;
-	if ! [[ $(TEST) == 6* ]]; then \
+	@if printf "$(TEST)" | grep -i -q "^6.*"; then \
+	  printf "\n===> Using integration TEST=$(TEST)\n"; \
+	else \
 	  printf "===> ${red}Aborting test-automate-upgrade as TEST ENV variable must start with 6, for example: 61_A2V1_migration_spec.rb${reset}\n"; \
 	  exit 3; \
 	fi;
 	@$(MAKE) start-es-pg;
-	@$(MAKE) run-log-level-info;
+	@$(MAKE) run;
 	# Give a few seconds for the background migrations to finish
 	sleep 20;
 	@if $(MAKE) test ; then \
@@ -458,14 +460,23 @@ test-scanner:
 # Run individual tests with: TEST="02_nodes_spec.rb" make test
 # or multiple ones with: TEST="02_*" make test
 test: generate-ruby-grpc wait-for-compliance-service
-	@printf "\n===> ${blue}Running tests...${reset}\n"; \
-	if [ -z "$$TEST" ] ; then TEST='*_spec.rb'; fi; \
+	@cd api/tests; \
+	pwd; \
+	printf "\n===> ${blue}Preparing to run tests...${reset}\n"; \
+	if [ -z "$$TEST" ]; then TEST='*_spec.rb'; fi; \
+	matching_tests=`ls -1q $$TEST 2> /dev/null | wc -l`; \
+	if [ $$matching_tests -eq 0 ]; then \
+		printf "\n${red}ERROR: TEST pattern $$TEST has not match, aborting...${reset}\n"; \
+		exit 17; \
+	else \
+	  @printf "\n===> ${blue}Running $$matching_tests test files...${reset}\n"; \
+	fi; \
 	bundler_version=`grep -A 1 "BUNDLED WITH" api/tests/Gemfile.lock | tail -1 | tr -d '[:space:]'`; \
 	gem install bundler -f --version "= $$bundler_version"; \
-	cd api/tests && \
-	printf "\n===> ${blue}Running 'bundle install' in api/tests...${reset}\n" && \
-	bundle install && \
-	printf "\n===> ${blue}Running the tests via run.rb...${reset}\n" && \
+	printf "\n===> ${blue}Running 'bundle install' in api/tests...${reset}\n"; \
+	pwd; \
+	bundle install; \
+	printf "\n===> ${blue}Running the tests via run.rb...${reset}\n"; \
 	PORT=$(PORT) \
 	SS_PORT=$(SS_PORT) \
 	MANAGER_PORT=$(MANAGER_PORT) \
@@ -478,7 +489,7 @@ test: generate-ruby-grpc wait-for-compliance-service
 	SSL_ROOT_CERT=$(SSL_ROOT_CERT) \
 	MARKET_PATH=$(MARKET_PATH) \
 	PROFILES_PATH=$(PROFILES_PATH) \
-	bundle exec ./run.rb $$TEST \
+	bundle exec ./run.rb $$TEST; \
 	echo
 
 test-prep: $(MARKET_PATH) $(PROFILES_PATH) start-ssh-node download-sample-market-profiles install-inspec start-es-pg
