studio: remove unnecessary ;'s from files touched in this PR
Signed-off-by: Steven Danna <steve@chef.io>

diff --git a/.studio/golang b/.studio/golang
--- a/.studio/golang
+++ b/.studio/golang
@@ -62,7 +62,7 @@ function go_test() {
   install_if_missing core/git git
 
   pushd "$scaffolding_go_pkg_path" >/dev/null
-    log_line "Executing Go test";
+    log_line "Executing Go test"
     # The default behavior is to run the package at the root of the
     # repository which is just as if we run: 'go test -cover'
     go test "$@" -cover $VERBOSE_TESTS
@@ -105,7 +105,7 @@ document "go_build_component" <<DOC
   A wrapper around the go_build to build a specific component.
 DOC
 function go_build_component() {
-  [[ "$1" == "" ]] && error "Missing component name argument; try 'describe ${FUNCNAME[0]}'" && return 1;
+  [[ "$1" == "" ]] && error "Missing component name argument; try 'describe ${FUNCNAME[0]}'" && return 1
   verify_component $1 || return $?
   local component=$1
 
@@ -173,7 +173,7 @@ function go_update_component() {
   local component=$1
 
   hab pkg path $HAB_ORIGIN/$component 2>/dev/null 1>&2 || hab pkg path chef/$component 2>/dev/null 1>&2
-  if [ $? -eq 0 ] ; then
+  if [ $? -eq 0 ]; then
     go_build_component $component
     reload_component_binary $component
   else
@@ -191,9 +191,9 @@ document "kill_running_service" <<DOC
       kill_running_service ingest-service
 DOC
 function kill_running_service() {
-  [[ "$1" == "" ]] && error "Missing component name argument" && return 1;
+  [[ "$1" == "" ]] && error "Missing component name argument" && return 1
   verify_component $1 || return $?
-  local component=$1;
+  local component=$1
   SERVICE_PID=$(grep_component_pid $component)
   if [[ ! -z ${SERVICE_PID} ]]; then
     kill $SERVICE_PID
@@ -215,7 +215,7 @@ DOC
 function auto_go_update_component() {
   [ "x$1" == "x" ] && error "Missing component name argument; try 'describe ${FUNCNAME[0]}'" && return 1
   verify_component $1 || return $?
-  local component=$1;
+  local component=$1
 
   setup_go_workspace
 
@@ -243,7 +243,7 @@ function go_component_static_tests() {
 
   log_line "Collecting ${component}'s go files"
   local gofiles
-  gofiles=$(find components/$component/ -maxdepth 3 -name '*.go');
+  gofiles=$(find components/$component/ -maxdepth 3 -name '*.go')
   [ -z "$gofiles" ] && return 0
 
   log_line "Installing gofmt"
@@ -318,7 +318,7 @@ document "go_component_make" <<DOC
   Runs the given make target(s) for the given component inside the scaffolding_go_pkg_path
 DOC
 function go_component_make() {
-  [[ "$1" == "" ]] && error "Missing component name argument" && return 1;
+  [[ "$1" == "" ]] && error "Missing component name argument" && return 1
   setup_go_workspace
   local component_relpath=$1
   local component_path="$GOPATH/src/github.com/chef/automate/$component_relpath"
